export const roseHero = {
  badge: "OllyGarden Rose",
  titleLead: "Find and fix OpenTelemetry",
  titleRest: "instrumentation at the source",
  lede: "Rose is your personal AI engineer for observability and OpenTelemetry. It reviews your services, finds missing or low-value telemetry, and helps your team apply the right fix.",
  cta: "Scan your Repo for Free!",
} as const;

export const roseHow = {
  steps: [
    {
      n: "1",
      title: "Connect your repository",
      body: "Create an OllyGarden account and connect Rose to your GitHub repository.",
      image: "/images/rose/step-connect.svg",
      imageAlt: "OllyGarden connected to a GitHub repository",
    },
    {
      n: "2",
      title: "Get instrumentation findings",
      body: "Rose surfaces telemetry gaps, inconsistencies, and improvement opportunities that need attention.",
      image: "/images/rose/step-findings.png",
      imageAlt: "Rose surrounded by instrumentation findings",
    },
  ],
  apply: {
    n: "3",
    title: "Apply the fix",
    body: "Use Rose’s recommendations in the workflow that fits your team.",
    substeps: [
      {
        title: "Dashboard recommendations",
        body: "Review findings, explanations, and recommended changes from the OllyGarden dashboard.",
      },
      {
        title: "Pull requests",
        body: "Let Rose prepare source-level improvements from the dashboard for developer review.",
      },
      {
        title: "CLI + Coding Agents",
        soon: true,
        body: "Use Rose findings as context for your coding agent and apply OpenTelemetry improvements directly in your local workflow.",
      },
    ],
    issues: [
      { title: "Dashboard issue" },
      { title: "HTTP error" },
    ],
  },
} as const;

export const roseAction = {
  eyebrow: "Rose in Action",
  title: "See what Rose finds in your instrumentation",
  sub: "Watch OllyGarden Rose in action and see how it turns service analysis into practical OpenTelemetry recommendations your team can use.",
  video: {
    src: "/videos/meet-rose.mp4",
    label:
      "Demo video: Rose analyzing a repository and producing OpenTelemetry recommendations",
  },
} as const;

export const roseMatters = {
  eyebrow: "Why Rose Matters",
  title: "Instrumentation problems start in the code",
  paragraphs: [
    "As teams ship faster, instrumentation quality becomes harder to control. Developers, frameworks, and coding agents can repeat patterns that create noisy, incomplete, or misleading telemetry.",
    "Rose helps teams review OpenTelemetry instrumentation directly in the codebase, so problems can be fixed where they begin.",
  ],
  cards: [
    {
      title: "Missing telemetry",
      body: "Important operations can ship without the spans, logs, or attributes needed for debugging.",
      place: "tl",
    },
    {
      title: "Low-value instrumentation",
      body: "Some telemetry adds volume without adding useful context.",
      place: "bl",
    },
    {
      title: "Inconsistent patterns",
      body: "Different teams and services instrument similar workflows in different ways.",
      place: "tr",
    },
    {
      title: "Agent-generated mistakes",
      body: "Coding agents can reproduce bad instrumentation patterns unless they are guided by OpenTelemetry expertise.",
      place: "br",
    },
  ],
} as const;

export const roseClients = {
  title: "Listen from our clients",
  quotes: [
    {
      name: "Rob Chapman",
      role: "Founder / Observability Consultant",
      image: "/images/rose/avatar-rob.png",
      imageAlt: "Rob Chapman, Founder and Observability Consultant",
      paragraphs: [
        "Juraci gave me a demo of Rose yesterday. I left the call excited. Wired it up to my repo, ran it on a project I suspected had issues, and was gobsmacked. It found a real instrumentation problem on the first pass, it then raised a perfect PR to fix it.",
        "I want to be embarrassed about my own instrumentation.",
        "I am not though. I am excited for the possibilities, even if that means I need a new career.",
      ],
    },
    {
      name: "Elena Kovalenko",
      role: "Principal Software Engineer",
      image: "/images/rose/avatar-elena.png",
      imageAlt: "Elena Kovalenko, Principal Software Engineer",
      paragraphs: [
        "By offloading a tedious migration with Rose, we save our engineering capacity for key business priorities and creative work.",
      ],
    },
    {
      name: "Marcin Siennicki",
      role: "Advanced Software Engineer",
      image: "/images/rose/avatar-marcin.png",
      imageAlt: "Marcin Siennicki, Advanced Software Engineer",
      paragraphs: [
        "Another great result from ROSE 🚀 It helped me identify that operational spans generated by route such as /metrics were being ingested without sampling, despite providing minimal value to the team. After introducing sampling, I reduced the span rate from 14 spans/sec to 8 spans/sec, lowering telemetry volume (can't past the screen unfortunately).",
      ],
    },
  ],
} as const;

export const roseContext = {
  eyebrow: "Context-Aware Analysis",
  titleLead: "Rooted in OpenTelemetry",
  titleRest: "Curated by OllyGarden",
  paragraphs: [
    "Rose understands your codebase, not just isolated changes. It connects patterns across services with OpenTelemetry standards, OllyGarden’s instrumentation expertise, and your organization’s preferences.",
    "The result is practical, consistent recommendations that are easier for developers to apply and maintain.",
  ],
  nodes: [
    { id: "tl", title: "OllyGarden", sub: "Knowledge Base" },
    { id: "tr", title: "OTel Specs", sub: "Official standards" },
    { id: "bl", title: "Codebase", sub: "Full context" },
    { id: "br", title: "Your Organization", sub: "Learns across applications" },
  ],
} as const;

export const rosePlans = {
  eyebrow: "Get Started",
  title: "Choose how you want to use Rose",
  sub: "All plans include the full codebase scan, the instrumentation dashboard, and access to the REST API (e.g. via OllyGarden CLI). Open Source access is granted upon review.",
  free: {
    title: "Free",
    note: "No credit card required",
    cta: "Get Started",
    href: "/get-started",
    items: [
      "Up to 5 repositories included",
      "Weekly automatic instrumentation review",
      "Instrumentation dashboard",
      "REST API and CLI access",
      "Custom review instructions",
      "Additional repositories for $5/month each",
    ],
  },
  enterprise: {
    title: "Enterprise",
    note: "Contact us to start",
    cta: "Contact Us",
    href: "/contact",
    items: [
      "Everything in Free",
      "On-demand instrumentation reviews",
      "Autonomous instrumentation improvements",
      "Agentic Instrumentation (MVI)",
      "Team integrations for Slack, Discord, and more",
      "Priority support with a dedicated channel",
    ],
  },
  openSource: {
    title: "Open Source",
    note: "Access granted upon request",
    cta: "Apply Now",
    href: "/contact",
    items: [
      "Everything in Free",
      "Unlimited public repositories",
      "Priority access for CNCF projects",
    ],
  },
} as const;

export const roseCta = {
  title: "Start with a repository scan",
  sub: "Connect Rose to your repository and see where your OpenTelemetry instrumentation can be improved. Get actionable findings, review the recommendations, and help your team fix telemetry issues at the source.",
  primary: { label: "Scan your Repo for Free!" },
  secondary: { label: "Book a Demo", href: "/contact" },
} as const;

export const roseMeta = {
  title: "OllyGarden Rose — Find and fix OpenTelemetry instrumentation at the source",
  description: roseHero.lede,
  path: "/products/rose",
} as const;
